import time

# This scale factor needs to be passed in based on the plotter's mechanics (steps per mm)
# A larger scale will make the drawing bigger.
WORKSPACE_MM = 100.0  # 10x10 cm page

def _normalize_contours(contours):
    """Normalize contours to fit inside a WORKSPACE_MM x WORKSPACE_MM box.

    This computes the bounding box of all points and scales/translates them
    so they fit into [0, WORKSPACE_MM] in both axes, preserving aspect ratio.
    """
    if not contours:
        return contours

    xs = []
    ys = []
    for contour in contours:
        for pt in contour:
            x, y = pt[0]
            xs.append(x)
            ys.append(y)

    if not xs or not ys:
        return contours

    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)

    range_x = max_x - min_x if max_x > min_x else 1.0
    range_y = max_y - min_y if max_y > min_y else 1.0

    scale = min(WORKSPACE_MM / range_x, WORKSPACE_MM / range_y)

    # Center in workspace
    offset_x = (WORKSPACE_MM - range_x * scale) / 2.0
    offset_y = (WORKSPACE_MM - range_y * scale) / 2.0

    normalized = []
    for contour in contours:
        new_contour = []
        for pt in contour:
            x, y = pt[0]
            nx = (x - min_x) * scale + offset_x
            ny = (y - min_y) * scale + offset_y
            new_contour.append([[nx, ny]])
        normalized.append(new_contour)
    return normalized


def draw(contours, controller, serial_controller, scale, progress_callback=None, preview_canvas=None):
    """
    Draws the given contours on a plotter that uses relative move commands.
    It tracks the virtual coordinates and calculates the required relative
    steps for each movement.

    :param contours: A list of contours (from OpenCV).
    :param controller: A PlotterController for pause/stop logic.
    :param serial_controller: A PlotterSerial object for sending commands.
    :param scale: Steps per mm (float)
    :param progress_callback: An optional function to call with progress updates.
    :param preview_canvas: Optional PreviewCanvas widget for live visualization.
    """
    current_x = 0
    current_y = 0
    steps_drawn = 0

    # Normalize contours into 100x100 mm workspace
    contours = _normalize_contours(contours)

    # Start with the pen up
    serial_controller.pen_up()
    if preview_canvas:
        preview_canvas.set_pen_down(False)
    time.sleep(0.5) # Give the servo time to lift

    for contour in contours:
        if not controller.wait_if_paused():
            return # Exit if stopped

        if len(contour) < 2: # Need at least two points to draw a line
            continue

        # --- 1. Move to the start of the contour (with pen up) ---
        start_point = contour[0][0]
        target_x = start_point[0] * scale
        target_y = start_point[1] * scale
        
        dx = target_x - current_x
        dy = target_y - current_y

        serial_controller.move(int(dx), int(dy))
        if preview_canvas:
            preview_canvas.move_pen(dx / scale, dy / scale)
        current_x = target_x
        current_y = target_y
        steps_drawn += 1
        if progress_callback:
            progress_callback(steps_drawn)

        # --- 2. Lower the pen to start drawing ---
        serial_controller.pen_down()
        if preview_canvas:
            preview_canvas.set_pen_down(True)
        time.sleep(0.5) # Give the servo time to lower

        # --- 3. Draw the rest of the contour lines ---
        for point in contour[1:]:
            if not controller.wait_if_paused():
                serial_controller.pen_up() # Lift pen if stopped mid-draw
                return

            target_x = point[0][0] * scale
            target_y = point[0][1] * scale
            
            dx = target_x - current_x
            dy = target_y - current_y
            
            serial_controller.move(int(dx), int(dy))
            if preview_canvas:
                preview_canvas.move_pen(dx / scale, dy / scale)
            current_x = target_x
            current_y = target_y
            steps_drawn += 1
            if progress_callback:
                progress_callback(steps_drawn)
        
        # --- 4. Lift the pen after finishing the contour ---
        serial_controller.pen_up()
        if preview_canvas:
            preview_canvas.set_pen_down(False)
        time.sleep(0.5)

    # Redundant homing removed - handled by main app via hardware HOME command
    # serial_controller.move(int(-current_x), int(-current_y))
    # if progress_callback: progress_callback(steps_drawn + 1)

def draw_actions(actions, controller, serial_controller, scale, progress_callback=None, preview_canvas=None, tool_change_callback=None):
    """
    Executes a list of actions generated by text_to_actions.
    
    :param actions: List of actions [('PEN_UP',), ('MOVE', dx, dy), ...]
    :param controller: PlotterController
    :param serial_controller: PlotterSerial
    :param progress_callback: Function(steps_drawn)
    :param preview_canvas: Optional PreviewCanvas widget for live visualization.
    :param tool_change_callback: Optional function(tool_number) -> bool for GUI dialog
    """
    steps_drawn = 0
    current_x = 0
    current_y = 0
    
    # Ensure pen is up at start
    serial_controller.pen_up()
    if preview_canvas:
        preview_canvas.set_pen_down(False)
    time.sleep(0.5)

    for action in actions:
        if not controller.wait_if_paused():
            return

        cmd = action[0]
        
        if cmd == 'PEN_UP':
            serial_controller.pen_up()
            if preview_canvas:
                preview_canvas.set_pen_down(False)
            time.sleep(0.2)
        elif cmd == 'PEN_DOWN':
            serial_controller.pen_down()
            if preview_canvas:
                preview_canvas.set_pen_down(True)
            time.sleep(0.5)  # Increased delay to ensure pen is fully down before first move
        elif cmd == 'MOVE':
            dx, dy = action[1], action[2]
            
            scaled_dx = int(dx * scale)
            scaled_dy = int(dy * scale)
            
            serial_controller.move(scaled_dx, scaled_dy)
            
            if preview_canvas:
                preview_canvas.move_pen(dx, dy)
            
            current_x += scaled_dx
            current_y += scaled_dy
        elif cmd == 'TOOL_CHANGE':
            # Tool change - pause and wait for user to swap pen
            tool_number = action[1]
            
            # If GUI callback provided, show dialog
            if tool_change_callback:
                confirmed = tool_change_callback(tool_number)
                if not confirmed:
                    # User cancelled - stop drawing
                    controller.stop()
                    return
            
            # Send tool change command to hardware
            serial_controller.tool_change(tool_number)
            
            # Update preview canvas color if available
            if preview_canvas:
                color_map = {0: '#FFFFFF', 1: '#FF4444', 2: '#4444FF', 3: '#44FF44', 4: '#FFFF44', 5: '#FF8844'}
                preview_canvas.set_pen_color(color_map.get(tool_number, '#FFFFFF'))
        
        steps_drawn += 1
        if progress_callback:
            progress_callback(steps_drawn)
            
    # Redundant homing removed - handled by main app via hardware HOME command
    # serial_controller.pen_up()
    # time.sleep(0.2)
    # serial_controller.move(-current_x, -current_y)
    # if progress_callback: progress_callback(steps_drawn + 1)
